// ============== LANGUAGE CONTEXT ==============
// Contexte global pour la gestion des langues et traductions

import React, { createContext, useContext, useState, useEffect } from 'react';

// Langues disponibles
export const LANGUAGES = {
    fr: {
        code: 'fr',
        name: 'Français',
        flag: '🇫🇷'
    },
    en: {
        code: 'en',
        name: 'English',
        flag: '🇺🇸'
    }
};

// Traductions par langue
const translations = {
    fr: {
        // Header
        'header.title': 'Planificateur C-Secur360',
        'header.subtitle': 'Version 6.7 - Gestion d\'équipes et projets',
        'header.login': 'Se connecter',
        'header.logout': 'Se déconnecter',
        'header.adminMode': 'Mode Administrateur',
        'header.exitAdmin': 'Quitter mode Admin',
        'header.month': 'Mois',
        'header.week': 'Semaine',
        'header.allOffices': 'Tous les bureaux',

        // Navigation
        'nav.calendar': 'Calendrier',
        'nav.personnel': 'Personnel',
        'nav.equipment': 'Équipements',
        'nav.jobs': 'Tâches',

        // Formulaires
        'form.save': 'Enregistrer',
        'form.cancel': 'Annuler',
        'form.close': 'Fermer',
        'form.add': 'Ajouter',
        'form.edit': 'Modifier',
        'form.delete': 'Supprimer',
        'form.search': 'Rechercher',
        'form.filter': 'Filtrer',
        'form.searchPlaceholder': 'Rechercher...',

        // Filtres
        'filter.filters': 'Filtres',
        'filter.filtersAndOptions': 'Filtres et Options',
        'filter.menuFilters': 'Menu des filtres',
        'filter.type': 'Type',
        'filter.bureau': 'Bureau',
        'filter.office': 'Bureau',
        'filter.position': 'Poste',
        'filter.view': 'Vue',
        'filter.selectViewType': 'Sélectionner le type de vue',
        'filter.filterByOffice': 'Filtrer par bureau/succursale',
        'filter.filterByPosition': 'Filtrer par poste',
        'filter.personnelOnly': 'Affichage du personnel uniquement',
        'filter.equipmentOnly': 'Affichage des équipements uniquement',
        'filter.globalView': 'Personnel et équipements ensemble',
        'filter.eventsOnly': 'Jobs sans ressources',
        'filter.dashboardView': 'Vue analytique avancée',
        'filter.individualViewMode': 'Mode vue individuelle',
        'filter.selectResource': 'Sélectionner la ressource',
        'filter.selectOption': 'Sélectionner...',
        'filter.individualViewDescription': 'Affiche le calendrier d\'une seule personne ou équipement',
        'filter.selectOfficeResource': 'Sélectionnez un bureau pour afficher uniquement les ressources de cette succursale',
        'filter.showPersonnelPosition': 'Affiche le personnel ayant le poste sélectionné',
        'filter.positionNotAvailable': 'Filtre par poste non disponible',
        'filter.selectPersonnelOrGlobal': 'Sélectionnez "Personnel" ou "Vue globale" dans l\'onglet Type',
        'filter.individualViewNotAvailable': 'Vue individuelle non disponible',
        'filter.dashboardFocus': 'Focus dashboard',
        'filter.chooseAnalysisType': 'Choisissez le type d\'analyse à afficher',

        // Jobs/Événements
        'job.title': 'Titre',
        'job.description': 'Description',
        'job.startDate': 'Date de début',
        'job.endDate': 'Date de fin',
        'job.startTime': 'Heure de début',
        'job.endTime': 'Heure de fin',
        'job.priority': 'Priorité',
        'job.status': 'Statut',
        'job.department': 'Département/Succursale',
        'job.personnel': 'Personnel',
        'job.equipment': 'Équipement',
        'job.customizeByDay': 'Personnaliser par jour',
        'job.selectResources': 'Sélectionner les ressources',
        'job.chooseAction': 'Choisir une action...',
        'job.selectAllResources': 'Sélectionner toutes les ressources',
        'job.cancelDailyCustomization': 'Annuler la personnalisation par jour',

        // Personnel
        'personnel.name': 'Nom',
        'personnel.department': 'Département/Succursale',
        'personnel.available': 'Disponible',
        'personnel.assigned': 'Assigné',

        // Équipements (définitions de base - les détaillées sont plus loin)
        'equipment.inUse': 'En cours d\'utilisation',
        'equipment.maintenance': 'En maintenance',
        'equipment.outOfService': 'Hors service',

        // Horaires
        'schedule.schedules': 'Horaires',
        'schedule.byDay': 'Par jour',
        'schedule.byDepartment': 'Par département/succursale',
        'schedule.global': 'Global',
        'schedule.custom': 'Personnalisé',
        'schedule.startTime': 'Heure de début',
        'schedule.endTime': 'Heure de fin',

        // Messages
        'message.saved': 'Enregistré avec succès',
        'message.deleted': 'Supprimé avec succès',
        'message.error': 'Une erreur s\'est produite',
        'message.confirm': 'Êtes-vous sûr ?',
        'message.noData': 'Aucune donnée disponible',

        // Jours de la semaine
        'day.monday': 'Lundi',
        'day.tuesday': 'Mardi',
        'day.wednesday': 'Mercredi',
        'day.thursday': 'Jeudi',
        'day.friday': 'Vendredi',
        'day.saturday': 'Samedi',
        'day.sunday': 'Dimanche',

        // Jours de la semaine (format court)
        'day.short.monday': 'Lun',
        'day.short.tuesday': 'Mar',
        'day.short.wednesday': 'Mer',
        'day.short.thursday': 'Jeu',
        'day.short.friday': 'Ven',
        'day.short.saturday': 'Sam',
        'day.short.sunday': 'Dim',

        // Mois
        'month.january': 'Janvier',
        'month.february': 'Février',
        'month.march': 'Mars',
        'month.april': 'Avril',
        'month.may': 'Mai',
        'month.june': 'Juin',
        'month.july': 'Juillet',
        'month.august': 'Août',
        'month.september': 'Septembre',
        'month.october': 'Octobre',
        'month.november': 'Novembre',
        'month.december': 'Décembre',

        // Mois (format court)
        'month.short.january': 'Jan',
        'month.short.february': 'Fév',
        'month.short.march': 'Mar',
        'month.short.april': 'Avr',
        'month.short.may': 'Mai',
        'month.short.june': 'Jun',
        'month.short.july': 'Jul',
        'month.short.august': 'Aoû',
        'month.short.september': 'Sep',
        'month.short.october': 'Oct',
        'month.short.november': 'Nov',
        'month.short.december': 'Déc',

        // Menu hamburger
        'menu.createEvent': 'Créer un événement',
        'menu.manageLeaves': 'Gestion des congés',
        'menu.manageResources': 'Gestion des ressources',
        'menu.settings': 'Paramètres',
        'menu.quickActions': 'Actions rapides',
        'menu.createEventDesc': 'Planifier un nouveau job',
        'menu.manageLeavesDesc': 'Gérer les demandes de congés',
        'menu.manageResourcesDesc': 'Personnel et équipements',
        'menu.preferences': 'Préférences',
        'menu.theme': 'Thème',

        // Application générale
        'app.loading': 'Chargement C-Secur360',
        'app.initializing': 'Initialisation du planificateur...',
        'app.welcome': 'Bienvenue',
        'app.version': 'Version 6.7',
        'app.modernInterface': 'Interface modernisée',

        // Connexion
        'login.title': 'Connexion',
        'login.username': 'Nom d\'utilisateur',
        'login.password': 'Mot de passe',
        'login.submit': 'Se connecter',
        'login.error': 'Identifiants incorrects',
        'login.required': 'Connexion requise',
        'login.userNotFound': 'Erreur: Utilisateur non trouvé',
        'login.passwordRequired': 'Erreur: Mot de passe requis',
        'login.accessGranted': 'Accès autorisé',
        'login.success': 'Connexion réussie',
        'login.logoutSuccess': 'Déconnexion réussie',
        'login.secureAuth': 'Authentification sécurisée',
        'login.searchPlaceholder': 'Tapez pour rechercher ou cliquez pour voir la liste...',

        // Notifications
        'notification.success': 'Succès',
        'notification.error': 'Erreur',
        'notification.warning': 'Attention',
        'notification.info': 'Information',
        'notification.resourcesAccess': 'Accès aux ressources autorisé pour cette session',

        // Permissions
        'permissions.modification': 'Modification',
        'permissions.coordinator': 'Coordinateur',
        'permissions.admin': 'Administrateur',

        // Calendrier
        'calendar.today': 'Aujourd\'hui',
        'calendar.week': 'Semaine',
        'calendar.month': 'Mois',
        'calendar.year': 'Année',
        'calendar.events': 'Événements',
        'calendar.noEvents': 'Aucun événement',
        'calendar.day': 'Journée',
        'calendar.1week': '1 Semaine',
        'calendar.2weeks': '2 Semaines',
        'calendar.3weeks': '3 Semaines',
        'calendar.1month': '1 Mois',
        'calendar.3months': '3 Mois',
        'calendar.6months': '6 Mois',
        'calendar.1year': '1 An',
        'calendar.detailedViews': 'Vues détaillées',
        'calendar.extendedPeriods': 'Périodes étendues',
        'calendar.goToDate': 'Aller à une date',
        'calendar.selectDateToNavigate': 'Sélectionnez une date pour y naviguer rapidement',
        'calendar.go': 'Aller',
        'calendar.doubleClickFullDate': 'Double-cliquez pour voir la date complète',
        'calendar.fullDate': 'Date complète',
        'calendar.colorMode': 'Mode de couleur des événements',
        'calendar.colorByBranch': 'Couleur par succursale',
        'calendar.colorByPriority': 'Couleur par priorité',
        'calendar.globalView': 'Vue globale',
        'calendar.individualView': 'Vue individuelle',
        'calendar.days': 'jours',
        'calendar.overview': 'Vue d\'ensemble',
        'calendar.planningRate': 'Taux de planification',

        // Modals génériques
        'modal.confirm': 'Confirmer',
        'modal.yes': 'Oui',
        'modal.no': 'Non',
        'modal.ok': 'OK',

        // Statuts
        'status.available': 'Disponible',
        'status.busy': 'Occupé',
        'status.unavailable': 'Indisponible',
        'status.planned': 'Planifié',
        'status.inProgress': 'En cours',
        'status.completed': 'Terminé',
        'status.cancelled': 'Annulé',

        // Actions utilisateur
        'action.add': 'Ajouter',
        'action.edit': 'Modifier',
        'action.delete': 'Supprimer',
        'action.save': 'Sauvegarder',
        'action.cancel': 'Annuler',
        'action.create': 'Créer',
        'action.new': 'Nouveau',
        'action.confirm': 'Confirmer',
        'action.close': 'Fermer',
        'action.search': 'Rechercher',
        'action.filter': 'Filtrer',

        // Messages d'erreur
        'error.required': 'Veuillez remplir tous les champs obligatoires',
        'error.requiredFields': 'Veuillez remplir les champs obligatoires: Numéro de projet, Client, Date début, Date fin et Département/Succursale en charge',
        'error.save': 'Erreur lors de la sauvegarde',
        'error.delete': 'Erreur lors de la suppression',
        'error.load': 'Erreur lors du chargement',
        'error.validation': 'Erreur de validation',
        'error.network': 'Erreur de connexion',

        // Messages de succès
        'success.saved': 'Sauvegardé avec succès',
        'success.deleted': 'Supprimé avec succès',
        'success.created': 'Créé avec succès',
        'success.updated': 'Mis à jour avec succès',

        // Modal et confirmations
        'modal.irreversible': 'Cette action est irréversible',
        'modal.areYouSure': 'Êtes-vous sûr ?',
        'modal.confirmDelete': 'Confirmer la suppression',
        'modal.confirmSave': 'Confirmer la sauvegarde',

        // Ressources
        'resource.personnel': 'Personnel',
        'resource.equipment': 'Équipement',
        'resource.allOffices': 'Tous les bureaux',
        'resource.allPositions': 'Tous les postes',
        'resource.department': 'Département',
        'resource.position': 'Poste',
        'resource.branch': 'Succursale',
        'resource.name': 'Nom',
        'resource.firstName': 'Prénom',
        'resource.nameFirstName': 'Nom / Prénom',
        'resource.type': 'Type',
        'resource.status': 'Statut',
        'resource.resource': 'Ressource',
        'resource.event': 'Événement',
        'resource.eventClient': 'Événement / Client',
        'resource.equipment.short': 'Équip.',
        'resource.technicians': 'techniciens',
        'resource.equipments': 'équipements',
        'resource.notDefined': 'Non défini',
        'resource.clientNotDefined': 'Client non défini',
        'resource.officeNotDefined': 'Bureau non défini',

        // Temps et planification
        'time.today': 'Aujourd\'hui',
        'time.thisWeek': 'Cette semaine',
        'time.thisMonth': 'Ce mois',
        'time.startDate': 'Date de début',
        'time.endDate': 'Date de fin',
        'time.startTime': 'Heure de début',
        'time.endTime': 'Heure de fin',
        'time.duration': 'Durée',

        // Événements et jobs
        'event.title': 'Titre de l\'événement',
        'event.description': 'Description',
        'event.create': 'Créer événement',
        'event.edit': 'Modifier l\'événement',
        'event.delete': 'Supprimer l\'événement',
        'event.customizeByDay': 'Personnaliser par jour',
        'event.recurrence': 'Récurrence',
        'event.priority': 'Priorité',
        'event.location': 'Emplacement',
        'event.eventsOnly': 'Événements seulement',
        'event.conflictEvent': 'Événement en conflit',
        'event.conflictWarning': 'Cet événement est en conflit avec l\'événement principal',
        'event.modifyEvent': 'Modifier cet événement',
        'event.assignedResources': 'Ressources assignées',

        // Types de vue
        'viewType.personnel': '👥 Personnel',
        'viewType.equipment': '🔧 Équipements',
        'viewType.global': '🌐 Vue globale',
        'viewType.events': '📋 Événements seulement',
        'viewType.dashboard': '📊 Dashboard',
        'viewType.globalFocus': '📊 Vue globale',
        'viewType.personnelFocus': '👥 Focus Personnel',
        'viewType.equipmentFocus': '🔧 Focus Équipements',

        // États et validation
        'validation.required': 'Champ requis',
        'validation.email': 'Email invalide',
        'validation.phone': 'Numéro de téléphone invalide',
        'validation.dateRange': 'Plage de dates invalide',

        // Interface générale
        'ui.loading': 'Chargement...',
        'ui.saving': '⏳ Sauvegarde...',
        'ui.deleting': 'Suppression...',
        'ui.noData': 'Aucune donnée disponible',
        'ui.noResults': 'Aucun résultat trouvé',
        'ui.selectOption': 'Sélectionner une option',
        'ui.selectAll': 'Tout sélectionner',
        'ui.viewAll': 'Voir tout',
        'ui.viewDetails': 'Voir les détails',
        'ui.hide': '🔼 Masquer',

        // Analytics et dashboard
        'analytics.dashboard': 'Dashboard Analytique',
        'analytics.totalEvents': 'Total Événements',
        'analytics.plannedHours': 'Heures Planifiées',
        'analytics.utilizationRate': 'Taux d\'utilisation',
        'analytics.efficiency': 'Efficacité',
        'analytics.thisWeek': 'Cette semaine',
        'analytics.export': 'Exporter',
        'analytics.overviewActivities': 'Vue d\'ensemble des activités sur',
        'analytics.personnelPlanning': 'Planification Personnel',
        'analytics.personnelRequired': 'Personnel requis',
        'analytics.personnelPlanned': 'Personnel planifié',
        'analytics.planningRate': 'Taux de planification',
        'analytics.distributionByPriority': 'Répartition par Priorité',
        'analytics.distributionByOffice': 'Répartition par Bureau',
        'analytics.inProgress': 'En Cours',
        'analytics.tentative': 'Tentatif',
        'analytics.waiting': 'En Attente',
        'analytics.description': 'Description',

        // Analytics Dashboard - nouvelles traductions
        'analytics.performanceAnalysis': 'Analyse de performance et achalandage',
        'analytics.thisYear': 'Cette année',
        'analytics.performance': 'Performance',
        'analytics.workload': 'Achalandage',
        'analytics.comparative': 'Comparatif',
        'analytics.individualAnalysis': 'Analyse Individuelle',
        'analytics.active': 'actifs',
        'analytics.totalProgrammed': 'Total programmé',
        'analytics.personnelAssigned': 'Personnel Assigné',
        'analytics.outOf': 'Sur',
        'analytics.highUtilization': 'Utilisation élevée',
        'analytics.moderateUtilization': 'Utilisation modérée',
        'analytics.lowUtilization': 'Utilisation faible',
        'analytics.trends30Days': 'Tendances (30 derniers jours)',
        'analytics.distributionByStatus': 'Répartition par Statut',
        'analytics.hoursPerDay': 'Heures par Jour',
        'analytics.performanceByOffice': 'Performance par Bureau',
        'analytics.utilizationRatePercent': 'Taux utilisation %',
        'analytics.detailsByOffice': 'Détails par Bureau',
        'analytics.hours': 'Heures',
        'analytics.availablePersonnel': 'Personnel Dispo',
        'analytics.assignedPersonnel': 'Personnel Assigné',
        'analytics.selectionForIndividualAnalysis': 'Sélection pour Analyse Individuelle',
        'analytics.analysisType': 'Type d\'analyse',
        'analytics.selectEmployee': 'Sélectionner un employé',
        'analytics.selectEquipment': 'Sélectionner un équipement',
        'analytics.chooseEmployee': 'Choisir un employé...',
        'analytics.chooseEquipment': 'Choisir un équipement...',
        'analytics.assignedEvents': 'Événements Assignés',
        'analytics.totalAssigned': 'Total assigné',
        'analytics.highWorkload': 'Charge élevée',
        'analytics.moderateWorkload': 'Charge modérée',
        'analytics.lowWorkload': 'Charge faible',
        'analytics.trends': 'Tendances',
        'analytics.noAssignedEvents': 'Aucun événement assigné',
        'analytics.eventWithoutName': 'Événement sans nom',
        'analytics.selectForDetailedAnalysis': 'Sélectionnez un {type} pour voir son analyse détaillée',
        'analytics.employee': 'employé',
        'analytics.equipment': 'équipement',
        'analytics.performanceTrends': 'Tendances de performance',
        'analytics.eventDistribution': 'Répartition des événements',
        'analytics.detailedHistory': 'Historique détaillé',
        'calendar.date': 'Date',

        // Leave Management
        'leave.vacation': 'Vacances',
        'leave.sickness': 'Maladie',
        'leave.personal': 'Personnel',
        'leave.training': 'Formation',
        'leave.maternity': 'Maternité/Paternité',
        'leave.other': 'Autre',
        'leave.fillRequiredFields': 'Veuillez remplir tous les champs obligatoires',
        'leave.startDateAfterEndDate': 'La date de début ne peut pas être postérieure à la date de fin',
        'leave.unknown': 'Inconnu',
        'leave.saveError': 'Erreur lors de la sauvegarde du congé',
        'leave.confirmDelete': 'Êtes-vous sûr de vouloir supprimer cette demande de congé ?',
        'leave.deleteError': 'Erreur lors de la suppression du congé',
        'leave.approvalError': 'Erreur lors de l\'approbation du congé',
        'leave.approved': 'Approuvé',
        'leave.refused': 'Refusé',
        'leave.pending': 'En attente',
        'leave.management': 'Gestion des Congés',
        'leave.requests': 'Demandes',
        'leave.newRequest': 'Nouvelle Demande',
        'leave.history': 'Historique',
        'leave.noPendingRequests': 'Aucune demande de congé en attente',
        'leave.period': 'Période',
        'leave.reason': 'Motif',
        'leave.requestedOn': 'Demandé le',
        'leave.approve': 'Approuver',
        'leave.refuse': 'Refuser',
        'leave.selectPerson': 'Sélectionner une personne...',
        'leave.type': 'Type de congé',
        'leave.reasonOptional': 'Motif (optionnel)',
        'leave.reasonPlaceholder': 'Ajoutez des détails sur la demande de congé...',
        'leave.createRequest': '💾 Créer la demande',
        'leave.noHistory': 'Aucun congé dans l\'historique',
        'leave.processedOn': 'Traité le',
        'leave.day': 'jour',
        'leave.days': 'jours',

        // Equipment Management
        'equipment.typeVehicle': 'Véhicule',
        'equipment.typeElectricTool': 'Outil électrique',
        'equipment.typeManualTool': 'Outil manuel',
        'equipment.typeSafety': 'Équipement sécurité',
        'equipment.typeElectricMaterial': 'Matériel électrique',
        'equipment.typePlumbing': 'Matériel plomberie',
        'equipment.typeScaffolding': 'Échafaudage',
        'equipment.typeCrane': 'Grue',
        'equipment.typeCompressor': 'Compresseur',
        'equipment.typeGenerator': 'Générateur',
        'equipment.typePump': 'Pompe',
        'equipment.typeWelding': 'Soudure',
        'equipment.typeMeasure': 'Mesure',
        'equipment.typeComputer': 'Informatique',
        'equipment.typeOther': 'Autre',
        'equipment.nameRequired': 'Le nom de l\'\u00e9quipement est requis',
        'equipment.saveError': 'Erreur lors de la sauvegarde de l\'\u00e9quipement',
        'equipment.confirmDelete': 'Êtes-vous sûr de vouloir supprimer {name} ?\n\nCette action est irréversible.',
        'equipment.deleteError': 'Erreur lors de la suppression de l\'\u00e9quipement',
        'equipment.modify': 'Modifier l\'\u00c9quipement',
        'equipment.new': 'Nouvel \u00c9quipement',
        'equipment.name': 'Nom de l\'\u00e9quipement',
        'equipment.namePlaceholder': 'Ex: Perceuse sans fil Makita',
        'equipment.type': 'Type',
        'equipment.typePlaceholder': 'Ex: Outil électrique',
        'equipment.brand': 'Marque',
        'equipment.brandPlaceholder': 'Ex: Makita',
        'equipment.model': 'Modèle',
        'equipment.modelPlaceholder': 'Ex: XDT131',
        'equipment.serialNumber': 'Numéro de série',
        'equipment.serialPlaceholder': 'Ex: SNJ123456789',
        'equipment.purchaseDate': 'Date d\'achat',
        'equipment.rentalCost': 'Coût de location ($/jour)',
        'equipment.costPlaceholder': 'Ex: 25.50',
        'equipment.nextMaintenance': 'Prochaine maintenance',
        'equipment.displayColor': 'Couleur d\'affichage',
        'equipment.status': 'Statut',
        'equipment.available': '🟢 Disponible',
        'equipment.unavailable': '🔴 Indisponible',
        'equipment.maintenanceScheduled': 'Maintenance prévue dans {days} {unit}',
        'equipment.maintenanceOverdue': 'Maintenance en retard de {days} {unit}',
        'equipment.notes': 'Notes',
        'equipment.notesPlaceholder': 'Ajoutez des notes sur cet équipement (maintenance, problèmes, etc.)',
        'equipment.equipment': 'Équipement',

        // Dashboard
        'dashboard.title': 'Dashboard de Gestion',
        'dashboard.operationsOverview': 'Vue d\'ensemble des opérations',
        'dashboard.connectedAs': 'Connecté',
        'dashboard.guestMode': 'Mode invité',
        'dashboard.overview': 'Vue d\'ensemble',
        'dashboard.resources': 'Ressources',
        'dashboard.analytics': 'Analytiques',
        'dashboard.unassigned': 'Non assigné',
        'dashboard.processRequests': 'Traiter les demandes',
        'dashboard.requireMaintenance': 'nécessite une maintenance prochainement',
        'dashboard.viewEquipment': 'Voir les équipements',
        'dashboard.totalJobs': 'Total Jobs',
        'dashboard.available': 'disponibles',
        'dashboard.completionRate': 'Taux de Complétion',
        'dashboard.outOf': 'sur',
        'dashboard.personnelUtilization': 'Utilisation Personnel',
        'dashboard.assigned': 'assignés',
        'dashboard.equipmentUtilization': 'Utilisation Équipements',
        'dashboard.used': 'utilisés',
        'dashboard.jobsByPriority': 'Jobs par Priorité',
        'dashboard.jobsByOffice': 'Jobs par Bureau',
        'dashboard.recentJobs': 'Jobs Récents (7 derniers jours)',
        'dashboard.noRecentJobs': 'Aucun job créé récemment',
        'dashboard.jobManagement': 'Gestion des Jobs',
        'dashboard.jobManagementPlaceholder': 'Interface de gestion des jobs à implémenter...',
        'dashboard.resourceManagement': 'Gestion des Ressources',
        'dashboard.resourceManagementPlaceholder': 'Interface de gestion des ressources à implémenter...',
        'dashboard.advancedAnalytics': 'Analytiques Avancées',
        'dashboard.advancedAnalyticsPlaceholder': 'Graphiques et analyses avancées à implémenter...',
        'leave.request': 'demande',

        // Priorités
        'priority.low': 'Faible',
        'priority.normal': 'Normale',
        'priority.high': 'Haute',
        'priority.urgent': 'Urgente',

        // Nouveaux statuts
        'status.postponed': 'Reporté',

        // Formulaire JobModal
        'form.form': 'Formulaire',
        'form.gantt': 'Gantt',
        'form.resources': 'Ressources',
        'form.projectNumber': 'Numéro de projet',
        'form.projectNumberPlaceholder': 'Ex: G25-1112, MDL-2024-001, CFM-240918',
        'form.clientPlaceholder': 'Nom du client',
        'form.departmentInCharge': 'Département/Succursale en charge',
        'form.selectDepartment': 'Sélectionner une departement',
        'form.jobName': 'Nom du job',
        'form.jobDescriptionPlaceholder': 'Ex: Installation électrique, description détaillée du job...',
        'form.schedulesByDay': 'Horaires par jour',
        'form.customizeSchedulesHint': 'Personnalisez les horaires pour des jours spécifiques. La case "Inclure les fins de semaine" ci-dessus contrôle l\'inclusion automatique.',
        'form.personnelStatistics': 'Statistiques du personnel',
        'form.total': 'Total',
        'form.planned': 'Planifiés',
        'form.available': 'Disponibles',
        'form.byDepartment': 'Par département/succursale',
        'form.byPosition': 'Par poste',
        'form.subcontractorAdded': 'Sous-traitant ajouté avec succès',
        'form.addToGlobal': 'Ajouter au global',
        'form.removeFromGlobal': 'Retirer du global',
        'form.quickSelectionByDay': 'Sélection rapide par jour',
        'form.managePersonnelForDay': 'Gérer le personnel de ce jour',
        'form.manageEquipmentForDay': 'Gérer les équipements de ce jour',
        'form.durationInHours': 'Durée en heures',
        'form.openConflictEvent': 'Ouvrir l\'\u00e9vénement en conflit',

        // Job et maintenance
        'job.editExistingEvent': 'Modification d\'un événement existant',
        'job.newJobInPlanner': 'Nouveau job dans le planificateur',
        'job.maintenance': 'Maintenance',
        'job.preventive': 'préventive',

        // Ressources
        'resource.notAssigned': 'Non assigné',

        // Messages de succès JobModal
        'success.eventSaved': 'Événement sauvegardé avec succès',
        'success.jobDeleted': 'Job supprimé avec succès',
        'success.personnelAddedToEvent': 'Personnel ajouté à l\'ensemble de l\'\u00e9vénement',

        // Messages d'avertissement
        'warning.personnelRemovedFromEvent': 'Personnel retiré de l\'ensemble de l\'\u00e9vénement',

        // Erreurs JobModal
        'error.saveError': 'Erreur lors de la sauvegarde',
        'error.deleteError': 'Erreur lors de la suppression',

        // Confirmations
        'modal.confirmDeleteJob': 'Êtes-vous sûr de vouloir supprimer ce job ?',

        // Équipements
        'equipment.currentlyOutOfService': 'Cet équipement est actuellement hors service',

        // Administration générale
        'admin.notSpecified': 'Non renseigné',

        // Administration des ressources
        'admin.resource.title': 'Gestion des Ressources',
        'admin.resource.subtitle': 'Personnel et Équipements',

        // Authentification admin
        'admin.auth.restrictedAccess': 'Accès Restreint',
        'admin.auth.authRequired': 'Cette section nécessite une authentification administrative.',
        'admin.auth.adminPassword': 'Mot de passe administrateur',
        'admin.auth.passwordPlaceholder': 'Entrez le mot de passe admin...',
        'admin.auth.hidePassword': 'Masquer le mot de passe',
        'admin.auth.showPassword': 'Afficher le mot de passe',
        'admin.auth.authenticate': 'Authentifier',

        // Vues administratives
        'admin.view.grid': 'Grille',
        'admin.view.individual': 'Individuelle',
        'admin.view.backToList': 'Retour à la liste',

        // Filtres administratifs
        'admin.filter.all': 'Tous',
        'admin.filter.allTypes': 'Tous les types',
        'admin.filter.availability': 'Disponibilité',
        'admin.filter.searchPlaceholder': 'Nom, poste, type...',
        'admin.filter.reset': 'Réinitialiser les filtres',
        'admin.filter.management': 'Gestion Filtres',
        'admin.filter.import': 'Importer',
        'admin.filter.export': 'Exporter',
        'admin.filter.newFilter': 'Nouveau Filtre',
        'admin.filter.createNew': 'Créer un nouveau filtre',
        'admin.filter.name': 'Nom du filtre',
        'admin.filter.namePlaceholder': 'Ex: Personnel Bureau Paris',
        'admin.filter.description': 'Description',
        'admin.filter.descriptionPlaceholder': 'Description optionnelle',
        'admin.filter.currentCriteria': 'Critères actuels qui seront sauvegardés',
        'admin.filter.tab': 'Onglet',
        'admin.filter.savedFilters': 'Filtres sauvegardés',
        'admin.filter.noSavedFilters': 'Aucun filtre sauvegardé',
        'admin.filter.configureHint': 'Configurez vos filtres et cliquez sur "Nouveau Filtre" pour les sauvegarder',
        'admin.filter.createdOn': 'Créé le',
        'admin.filter.apply': 'Appliquer',
        'admin.filter.nameRequired': 'Veuillez donner un nom à votre filtre',
        'admin.filter.savedSuccess': 'Filtre sauvegardé avec succès',
        'admin.filter.applied': 'Filtre appliqué',
        'admin.filter.confirmDelete': 'Êtes-vous sûr de vouloir supprimer ce filtre ?',
        'admin.filter.deleteSuccess': 'Filtre supprimé',
        'admin.filter.exportSuccess': 'Filtres exportés avec succès',
        'admin.filter.importSuccess': 'Filtre(s) importé(s) avec succès',
        'admin.filter.importError': 'Erreur lors de l\'importation des filtres',

        // Gestion du personnel
        'admin.personnel.management': 'Gestion du Personnel',
        'admin.personnel.add': 'Ajouter Personnel',
        'admin.personnel.contactInfo': 'Informations de contact',
        'admin.personnel.phone': 'Téléphone',
        'admin.personnel.email': 'Email',
        'admin.personnel.positionDetails': 'Détails du poste',
        'admin.personnel.skills': 'Compétences',
        'admin.personnel.skillsNotSpecified': 'Non renseignées',
        'admin.personnel.noResults': 'Aucun personnel trouvé avec les critères sélectionnés',

        // Gestion des équipements
        'admin.equipment.management': 'Gestion des Équipements',
        'admin.equipment.add': 'Ajouter Équipement',
        'admin.equipment.technicalInfo': 'Informations techniques',
        'admin.equipment.model': 'Modèle',
        'admin.equipment.serialNumber': 'Numéro de série',
        'admin.equipment.statusMaintenance': 'État et maintenance',
        'admin.equipment.condition': 'État',
        'admin.equipment.good': 'Bon',
        'admin.equipment.lastMaintenance': 'Dernière maintenance',
        'admin.equipment.nextMaintenance': 'Prochaine maintenance',
        'admin.equipment.notSpecified': 'Non renseignée',
        'admin.equipment.notPlanned': 'Non planifiée',
        'admin.equipment.notes': 'Notes',
        'admin.equipment.noNotes': 'Aucune note',
        'admin.equipment.noResults': 'Aucun équipement trouvé avec les critères sélectionnés',

        // Gestion des postes
        'admin.position.title': 'Postes',
        'admin.position.management': 'Gestion des Postes',
        'admin.position.add': 'Ajouter Poste',
        'admin.position.level': 'Niveau',
        'admin.position.salary': 'Salaire',
        'admin.position.noPositions': 'Aucun poste configuré',
        'admin.position.createHint': 'Commencez par créer les postes de votre entreprise',
        'admin.position.saveSuccess': 'Poste sauvegardé avec succès',

        // Gestion des succursales
        'admin.branch.title': 'Succursales',
        'admin.branch.management': 'Gestion des Succursales',
        'admin.branch.add': 'Ajouter Succursale',
        'admin.branch.active': 'Actif',
        'admin.branch.inactive': 'Inactif',
        'admin.branch.noBranches': 'Aucune succursale configurée',
        'admin.branch.saveSuccess': 'Succursale sauvegardée avec succès',

        // Personnel Modal - Général
        'personnel.newPersonnel': 'Nouveau Personnel',
        'personnel.general': 'Général',
        'personnel.skills': 'Compétences',
        'personnel.schedules': 'Horaires',
        'personnel.permissions': 'Permissions',
        'personnel.contact': 'Contact',
        'personnel.photo': 'Photo',
        'personnel.firstName': 'Prénom',
        'personnel.firstNamePlaceholder': 'Prénom...',
        'personnel.lastName': 'Nom',
        'personnel.lastNamePlaceholder': 'Nom de famille...',
        'personnel.position': 'Poste',
        'personnel.selectPosition': 'Sélectionner un poste...',
        'personnel.branch': 'Succursale',
        'personnel.hireDate': 'Date d\'embauche',
        'personnel.status': 'Statut',
        'personnel.statusActive': '✅ Actif',
        'personnel.statusInactive': '⏸️ Inactif',
        'personnel.statusOnLeave': '🏖️ En congé',
        'personnel.statusSick': '🤒 Maladie',
        'personnel.hourlyRate': 'Taux horaire ($)',
        'personnel.hourlyRatePlaceholder': 'Ex: 25.00',
        'personnel.annualSalary': 'Salaire annuel ($)',
        'personnel.annualSalaryPlaceholder': 'Ex: 50000',
        'personnel.systemAccess': 'Accès système',
        'personnel.password': 'Mot de passe',
        'personnel.passwordPlaceholder': 'Mot de passe...',
        'personnel.passwordChangeHint': 'Laisser vide pour ne pas changer',
        'personnel.calendarColor': 'Couleur calendrier',
        'personnel.visibleOnCalendar': 'Visible sur le calendrier',

        // Personnel Modal - Compétences
        'personnel.competencies': 'Compétences',
        'personnel.addSkill': 'Ajouter une compétence...',
        'personnel.certifications': 'Certifications',
        'personnel.addCertification': 'Ajouter une certification...',
        'personnel.trainings': 'Formations',
        'personnel.addTraining': 'Ajouter une formation...',

        // Personnel Modal - Horaires
        'personnel.workSchedules': 'Horaires de travail',
        'personnel.monday': 'lundi',
        'personnel.tuesday': 'mardi',
        'personnel.wednesday': 'mercredi',
        'personnel.thursday': 'jeudi',
        'personnel.friday': 'vendredi',
        'personnel.saturday': 'samedi',
        'personnel.sunday': 'dimanche',
        'personnel.to': 'à',
        'personnel.specialAvailability': 'Disponibilités spéciales',
        'personnel.availableWeekendsEmergency': 'Disponible weekends (urgence)',
        'personnel.availableNightWork': 'Disponible travail de nuit',
        'personnel.availableTravel': 'Disponible pour voyager',

        // Personnel Modal - Permissions
        'personnel.permissionsAccess': 'Permissions et accès',
        'personnel.canModify': 'Peut modifier les données',
        'personnel.canModifyDesc': 'Créer, modifier et supprimer des jobs',
        'personnel.isCoordinator': 'Coordinateur',
        'personnel.isCoordinatorDesc': 'Accès complet à toutes les fonctionnalités',
        'personnel.canApproveLeaves': 'Peut approuver les congés',
        'personnel.canApproveLeavesDesc': 'Valider ou refuser les demandes de congés',
        'personnel.canViewReports': 'Peut voir les rapports',
        'personnel.canViewReportsDesc': 'Accès aux statistiques et rapports',
        'personnel.canManagePersonnel': 'Peut gérer le personnel',
        'personnel.canManagePersonnelDesc': 'Ajouter, modifier et supprimer des employés',
        'personnel.canManageEquipment': 'Peut gérer les équipements',
        'personnel.canManageEquipmentDesc': 'Gérer les équipements et leur maintenance',
        'personnel.onlyCoordinatorsCanModify': 'Seuls les coordinateurs peuvent modifier les permissions d\'accès.',

        // Personnel Modal - Contact
        'personnel.officePhone': 'Téléphone bureau',
        'personnel.cellPhone': 'Cellulaire',
        'personnel.email': 'Email',
        'personnel.address': 'Adresse',
        'personnel.addressPlaceholder': '123 Rue Example',
        'personnel.city': 'Ville',
        'personnel.cityPlaceholder': 'Thetford Mines',
        'personnel.postalCode': 'Code postal',
        'personnel.postalCodePlaceholder': 'G1X 1X1',
        'personnel.emergencyContact': 'Contact d\'urgence',
        'personnel.contactPerson': 'Personne à contacter',
        'personnel.contactPersonPlaceholder': 'Nom du contact...',
        'personnel.emergencyPhone': 'Téléphone d\'urgence',
        'personnel.medicalInfo': 'Informations médicales',
        'personnel.medicalNotes': 'Notes médicales',
        'personnel.medicalNotesPlaceholder': 'Restrictions, limitations...',
        'personnel.allergies': 'Allergies',
        'personnel.allergiesPlaceholder': 'Allergies connues...',

        // Personnel Modal - Validation et messages
        'personnel.nameRequired': 'Le nom est requis',
        'personnel.firstNameRequired': 'Le prénom est requis',
        'personnel.positionRequired': 'Le poste est requis',
        'personnel.invalidEmail': 'Format d\'email invalide',
        'personnel.passwordRequiredNew': 'Un mot de passe est requis pour un nouvel employé',
        'personnel.personnelModified': 'Personnel modifié',
        'personnel.personnelCreated': 'Personnel créé',
        'personnel.saveError': 'Erreur lors de la sauvegarde',
        'personnel.personnelDeleted': 'Personnel supprimé',
        'personnel.deleteError': 'Erreur lors de la suppression',
        'personnel.confirmDelete': 'Confirmer la suppression',
        'personnel.confirmDeleteMessage': 'Êtes-vous sûr de vouloir supprimer {firstName} {lastName} ? Cette action est irréversible.',
        'personnel.delete': 'Supprimer',
        'personnel.cancel': 'Annuler',
        'personnel.saving': 'Sauvegarde...',
        'personnel.modify': 'Modifier',
        'personnel.create': 'Créer',

        // Personnel Modal Resource - Ajouts
        'personnel.fillNameFirstName': 'Veuillez remplir le nom et prénom avant de générer un mot de passe',
        'personnel.branchRequired': 'La succursale est requise',
        'personnel.confirmDeleteMessageSimple': 'Êtes-vous sûr de vouloir supprimer {name} ?\n\nCette action est irréversible.',
        'personnel.modifyPersonnel': 'Modifier le Personnel',
        'personnel.managementC-Secur360': 'Gestion du personnel C-Secur360',
        'personnel.lastNameExample': 'Ex: Dupont',
        'personnel.firstNameExample': 'Ex: Jean',
        'personnel.departmentPlaceholder': 'Sélectionné selon le poste ou saisie manuelle',
        'personnel.selectBranch': 'Sélectionner une succursale',
        'personnel.phone': 'Téléphone',
        'personnel.authPassword': 'Mot de passe authentification',
        'personnel.authPasswordPlaceholder': 'Mot de passe pour l\'authentification principale',
        'personnel.hidePassword': 'Masquer le mot de passe',
        'personnel.showPassword': 'Afficher le mot de passe',
        'personnel.passwordInfo': 'Requis pour accéder à l\'application. Reconnaissance 24h puis mot de passe requis à nouveau.',
        'personnel.generatePasswordHint': '💡 Cliquez sur 🔄 pour générer automatiquement un mot de passe basé sur le nom/prénom',
        'personnel.generateAutoPassword': 'Générer un mot de passe automatique',
        'personnel.generate': 'Générer',
        'personnel.accessLevel': 'Niveau d\'accès',
        'personnel.accessConsultation': '👁️ Consultation seule',
        'personnel.accessModification': '✏️ Modification limitée',
        'personnel.accessCoordination': '🎯 Coordination',
        'personnel.accessAdministration': '🔑 Administration complète',
        'personnel.accessLevelInfo': 'Définit les permissions de l\'utilisateur dans le système',
        'personnel.salaryOptional': 'Salaire (optionnel)',
        'personnel.specialties': 'Spécialités',
        'personnel.addSpecialty': 'Ajouter une spécialité...',
        'personnel.statusAvailable': '🟢 Disponible',
        'personnel.statusUnavailable': '🔴 Indisponible',
        'personnel.display': 'Affichage',
        'personnel.visibilityInfo': 'Décochez pour masquer cette personne du calendrier principal',
        'personnel.notes': 'Notes',
        'personnel.notesPlaceholder': 'Ajoutez des notes sur ce personnel...',
        'personnel.save': '💾 Sauvegarder'
    },

    en: {
        // Header
        'header.title': 'C-Secur360 Planner',
        'header.subtitle': 'Version 6.7 - Team and Project Management',
        'header.login': 'Login',
        'header.logout': 'Logout',
        'header.adminMode': 'Administrator Mode',
        'header.exitAdmin': 'Exit Admin Mode',
        'header.month': 'Month',
        'header.week': 'Week',
        'header.allOffices': 'All Offices',

        // Navigation
        'nav.calendar': 'Calendar',
        'nav.personnel': 'Personnel',
        'nav.equipment': 'Equipment',
        'nav.jobs': 'Tasks',

        // Formulaires
        'form.save': 'Save',
        'form.cancel': 'Cancel',
        'form.close': 'Close',
        'form.add': 'Add',
        'form.edit': 'Edit',
        'form.delete': 'Delete',
        'form.search': 'Search',
        'form.filter': 'Filter',
        'form.searchPlaceholder': 'Search...',

        // Filtres
        'filter.filters': 'Filters',
        'filter.filtersAndOptions': 'Filters and Options',
        'filter.menuFilters': 'Filters menu',
        'filter.type': 'Type',
        'filter.bureau': 'Office',
        'filter.office': 'Office',
        'filter.position': 'Position',
        'filter.view': 'View',
        'filter.selectViewType': 'Select view type',
        'filter.filterByOffice': 'Filter by office/branch',
        'filter.filterByPosition': 'Filter by position',
        'filter.personnelOnly': 'Personnel only display',
        'filter.equipmentOnly': 'Equipment only display',
        'filter.globalView': 'Personnel and equipment together',
        'filter.eventsOnly': 'Jobs without resources',
        'filter.dashboardView': 'Advanced analytics view',
        'filter.individualViewMode': 'Individual view mode',
        'filter.selectResource': 'Select resource',
        'filter.selectOption': 'Select...',
        'filter.individualViewDescription': 'Display calendar for a single person or equipment',
        'filter.selectOfficeResource': 'Select an office to display only resources from this branch',
        'filter.showPersonnelPosition': 'Show personnel with selected position',
        'filter.positionNotAvailable': 'Position filter not available',
        'filter.selectPersonnelOrGlobal': 'Select "Personnel" or "Global View" in the Type tab',
        'filter.individualViewNotAvailable': 'Individual view not available',
        'filter.dashboardFocus': 'Dashboard focus',
        'filter.chooseAnalysisType': 'Choose the type of analysis to display',

        // Jobs/Événements
        'job.title': 'Title',
        'job.description': 'Description',
        'job.startDate': 'Start Date',
        'job.endDate': 'End Date',
        'job.startTime': 'Start Time',
        'job.endTime': 'End Time',
        'job.priority': 'Priority',
        'job.status': 'Status',
        'job.department': 'Department/Branch',
        'job.personnel': 'Personnel',
        'job.equipment': 'Equipment',
        'job.customizeByDay': 'Customize by Day',
        'job.selectResources': 'Select Resources',
        'job.chooseAction': 'Choose an action...',
        'job.selectAllResources': 'Select All Resources',
        'job.cancelDailyCustomization': 'Cancel Daily Customization',

        // Personnel
        'personnel.name': 'Last Name',
        'personnel.department': 'Department/Branch',
        'personnel.available': 'Available',
        'personnel.assigned': 'Assigned',

        // Équipements (définitions de base - les détaillées sont plus loin)
        'equipment.inUse': 'In Use',
        'equipment.maintenance': 'Under Maintenance',
        'equipment.outOfService': 'Out of Service',

        // Horaires
        'schedule.schedules': 'Schedules',
        'schedule.byDay': 'By Day',
        'schedule.byDepartment': 'By Department/Branch',
        'schedule.global': 'Global',
        'schedule.custom': 'Custom',
        'schedule.startTime': 'Start Time',
        'schedule.endTime': 'End Time',

        // Messages
        'message.saved': 'Saved successfully',
        'message.deleted': 'Deleted successfully',
        'message.error': 'An error occurred',
        'message.confirm': 'Are you sure?',
        'message.noData': 'No data available',

        // Jours de la semaine
        'day.monday': 'Monday',
        'day.tuesday': 'Tuesday',
        'day.wednesday': 'Wednesday',
        'day.thursday': 'Thursday',
        'day.friday': 'Friday',
        'day.saturday': 'Saturday',
        'day.sunday': 'Sunday',

        // Jours de la semaine (format court)
        'day.short.monday': 'Mon',
        'day.short.tuesday': 'Tue',
        'day.short.wednesday': 'Wed',
        'day.short.thursday': 'Thu',
        'day.short.friday': 'Fri',
        'day.short.saturday': 'Sat',
        'day.short.sunday': 'Sun',

        // Mois
        'month.january': 'January',
        'month.february': 'February',
        'month.march': 'March',
        'month.april': 'April',
        'month.may': 'May',
        'month.june': 'June',
        'month.july': 'July',
        'month.august': 'August',
        'month.september': 'September',
        'month.october': 'October',
        'month.november': 'November',
        'month.december': 'December',

        // Mois (format court)
        'month.short.january': 'Jan',
        'month.short.february': 'Feb',
        'month.short.march': 'Mar',
        'month.short.april': 'Apr',
        'month.short.may': 'May',
        'month.short.june': 'Jun',
        'month.short.july': 'Jul',
        'month.short.august': 'Aug',
        'month.short.september': 'Sep',
        'month.short.october': 'Oct',
        'month.short.november': 'Nov',
        'month.short.december': 'Dec',

        // Menu hamburger
        'menu.createEvent': 'Create Event',
        'menu.manageLeaves': 'Manage Leaves',
        'menu.manageResources': 'Manage Resources',
        'menu.settings': 'Settings',
        'menu.quickActions': 'Quick Actions',
        'menu.createEventDesc': 'Plan a new job',
        'menu.manageLeavesDesc': 'Manage leave requests',
        'menu.manageResourcesDesc': 'Personnel and equipment',
        'menu.preferences': 'Preferences',
        'menu.theme': 'Theme',

        // Application générale
        'app.loading': 'Loading C-Secur360',
        'app.initializing': 'Initializing planner...',
        'app.welcome': 'Welcome',
        'app.version': 'Version 6.7',
        'app.modernInterface': 'Modern Interface',

        // Connexion
        'login.title': 'Login',
        'login.username': 'Username',
        'login.password': 'Password',
        'login.submit': 'Login',
        'login.error': 'Invalid credentials',
        'login.required': 'Login required',
        'login.userNotFound': 'Error: User not found',
        'login.passwordRequired': 'Error: Password required',
        'login.accessGranted': 'Access granted',
        'login.success': 'Login successful',
        'login.logoutSuccess': 'Logout successful',
        'login.secureAuth': 'Secure Authentication',
        'login.searchPlaceholder': 'Type to search or click to see the list...',

        // Notifications
        'notification.success': 'Success',
        'notification.error': 'Error',
        'notification.warning': 'Warning',
        'notification.info': 'Information',
        'notification.resourcesAccess': 'Resources access granted for this session',

        // Permissions
        'permissions.modification': 'Modification',
        'permissions.coordinator': 'Coordinator',
        'permissions.admin': 'Administrator',

        // Calendrier
        'calendar.today': 'Today',
        'calendar.week': 'Week',
        'calendar.month': 'Month',
        'calendar.year': 'Year',
        'calendar.events': 'Events',
        'calendar.noEvents': 'No events',
        'calendar.day': 'Day',
        'calendar.1week': '1 Week',
        'calendar.2weeks': '2 Weeks',
        'calendar.3weeks': '3 Weeks',
        'calendar.1month': '1 Month',
        'calendar.3months': '3 Months',
        'calendar.6months': '6 Months',
        'calendar.1year': '1 Year',
        'calendar.detailedViews': 'Detailed Views',
        'calendar.extendedPeriods': 'Extended Periods',
        'calendar.goToDate': 'Go to a date',
        'calendar.selectDateToNavigate': 'Select a date to navigate quickly',
        'calendar.go': 'Go',
        'calendar.doubleClickFullDate': 'Double-click to see full date',
        'calendar.fullDate': 'Full Date',
        'calendar.colorMode': 'Event color mode',
        'calendar.colorByBranch': 'Color by branch',
        'calendar.colorByPriority': 'Color by priority',
        'calendar.globalView': 'Global View',
        'calendar.individualView': 'Individual View',
        'calendar.days': 'days',
        'calendar.overview': 'Overview',
        'calendar.planningRate': 'Planning Rate',

        // Modals génériques
        'modal.confirm': 'Confirm',
        'modal.yes': 'Yes',
        'modal.no': 'No',
        'modal.ok': 'OK',

        // Statuts
        'status.available': 'Available',
        'status.busy': 'Busy',
        'status.unavailable': 'Unavailable',
        'status.planned': 'Planned',
        'status.inProgress': 'In Progress',
        'status.completed': 'Completed',
        'status.cancelled': 'Cancelled',

        // Actions utilisateur
        'action.add': 'Add',
        'action.edit': 'Edit',
        'action.delete': 'Delete',
        'action.save': 'Save',
        'action.cancel': 'Cancel',
        'action.create': 'Create',
        'action.new': 'New',
        'action.confirm': 'Confirm',
        'action.close': 'Close',
        'action.search': 'Search',
        'action.filter': 'Filter',

        // Messages d'erreur
        'error.required': 'Please fill in all required fields',
        'error.requiredFields': 'Please fill in the required fields: Project Number, Client, Start Date, End Date and Department/Branch in charge',
        'error.save': 'Error while saving',
        'error.delete': 'Error while deleting',
        'error.load': 'Error while loading',
        'error.validation': 'Validation error',
        'error.network': 'Connection error',

        // Messages de succès
        'success.saved': 'Successfully saved',
        'success.deleted': 'Successfully deleted',
        'success.created': 'Successfully created',
        'success.updated': 'Successfully updated',

        // Modal et confirmations
        'modal.irreversible': 'This action is irreversible',
        'modal.areYouSure': 'Are you sure?',
        'modal.confirmDelete': 'Confirm deletion',
        'modal.confirmSave': 'Confirm save',

        // Ressources
        'resource.personnel': 'Personnel',
        'resource.equipment': 'Equipment',
        'resource.allOffices': 'All Offices',
        'resource.allPositions': 'All Positions',
        'resource.department': 'Department',
        'resource.position': 'Position',
        'resource.branch': 'Branch',
        'resource.name': 'Last Name',
        'resource.firstName': 'First Name',
        'resource.nameFirstName': 'Last Name / First Name',
        'resource.type': 'Type',
        'resource.status': 'Status',
        'resource.resource': 'Resource',
        'resource.event': 'Event',
        'resource.eventClient': 'Event / Client',
        'resource.equipment.short': 'Equip.',
        'resource.technicians': 'technicians',
        'resource.equipments': 'equipment',
        'resource.notDefined': 'Not defined',
        'resource.clientNotDefined': 'Client not defined',
        'resource.officeNotDefined': 'Office not defined',

        // Temps et planification
        'time.today': 'Today',
        'time.thisWeek': 'This Week',
        'time.thisMonth': 'This Month',
        'time.startDate': 'Start Date',
        'time.endDate': 'End Date',
        'time.startTime': 'Start Time',
        'time.endTime': 'End Time',
        'time.duration': 'Duration',

        // Événements et jobs
        'event.title': 'Event Title',
        'event.description': 'Description',
        'event.create': 'Create Event',
        'event.edit': 'Edit Event',
        'event.delete': 'Delete Event',
        'event.customizeByDay': 'Customize by Day',
        'event.recurrence': 'Recurrence',
        'event.priority': 'Priority',
        'event.location': 'Location',
        'event.eventsOnly': 'Events Only',
        'event.conflictEvent': 'Conflict Event',
        'event.conflictWarning': 'This event conflicts with the main event',
        'event.modifyEvent': 'Modify this event',
        'event.assignedResources': 'Assigned Resources',

        // Types de vue
        'viewType.personnel': '👥 Personnel',
        'viewType.equipment': '🔧 Equipment',
        'viewType.global': '🌐 Global View',
        'viewType.events': '📋 Events Only',
        'viewType.dashboard': '📊 Dashboard',
        'viewType.globalFocus': '📊 Global View',
        'viewType.personnelFocus': '👥 Personnel Focus',
        'viewType.equipmentFocus': '🔧 Equipment Focus',

        // États et validation
        'validation.required': 'Required field',
        'validation.email': 'Invalid email',
        'validation.phone': 'Invalid phone number',
        'validation.dateRange': 'Invalid date range',

        // Interface générale
        'ui.loading': 'Loading...',
        'ui.saving': '⏳ Saving...',
        'ui.deleting': 'Deleting...',
        'ui.noData': 'No data available',
        'ui.noResults': 'No results found',
        'ui.selectOption': 'Select an option',
        'ui.selectAll': 'Select all',
        'ui.viewAll': 'View all',
        'ui.viewDetails': 'View details',
        'ui.hide': '🔼 Hide',

        // Analytics et dashboard
        'analytics.dashboard': 'Analytics Dashboard',
        'analytics.totalEvents': 'Total Events',
        'analytics.plannedHours': 'Planned Hours',
        'analytics.utilizationRate': 'Utilization Rate',
        'analytics.efficiency': 'Efficiency',
        'analytics.thisWeek': 'This Week',
        'analytics.export': 'Export',
        'analytics.overviewActivities': 'Activities overview over',
        'analytics.personnelPlanning': 'Personnel Planning',
        'analytics.personnelRequired': 'Personnel required',
        'analytics.personnelPlanned': 'Personnel planned',
        'analytics.planningRate': 'Planning rate',
        'analytics.distributionByPriority': 'Distribution by Priority',
        'analytics.distributionByOffice': 'Distribution by Office',
        'analytics.inProgress': 'In Progress',
        'analytics.tentative': 'Tentative',
        'analytics.waiting': 'Waiting',
        'analytics.description': 'Description',

        // Analytics Dashboard - new translations
        'analytics.performanceAnalysis': 'Performance and workload analysis',
        'analytics.thisYear': 'This Year',
        'analytics.performance': 'Performance',
        'analytics.workload': 'Workload',
        'analytics.comparative': 'Comparative',
        'analytics.individualAnalysis': 'Individual Analysis',
        'analytics.active': 'active',
        'analytics.totalProgrammed': 'Total programmed',
        'analytics.personnelAssigned': 'Assigned Personnel',
        'analytics.outOf': 'Out of',
        'analytics.highUtilization': 'High utilization',
        'analytics.moderateUtilization': 'Moderate utilization',
        'analytics.lowUtilization': 'Low utilization',
        'analytics.trends30Days': 'Trends (last 30 days)',
        'analytics.distributionByStatus': 'Distribution by Status',
        'analytics.hoursPerDay': 'Hours per Day',
        'analytics.performanceByOffice': 'Performance by Office',
        'analytics.utilizationRatePercent': 'Utilization rate %',
        'analytics.detailsByOffice': 'Details by Office',
        'analytics.hours': 'Hours',
        'analytics.availablePersonnel': 'Available Personnel',
        'analytics.assignedPersonnel': 'Assigned Personnel',
        'analytics.selectionForIndividualAnalysis': 'Selection for Individual Analysis',
        'analytics.analysisType': 'Analysis type',
        'analytics.selectEmployee': 'Select an employee',
        'analytics.selectEquipment': 'Select equipment',
        'analytics.chooseEmployee': 'Choose an employee...',
        'analytics.chooseEquipment': 'Choose equipment...',
        'analytics.assignedEvents': 'Assigned Events',
        'analytics.totalAssigned': 'Total assigned',
        'analytics.highWorkload': 'High workload',
        'analytics.moderateWorkload': 'Moderate workload',
        'analytics.lowWorkload': 'Low workload',
        'analytics.trends': 'Trends',
        'analytics.noAssignedEvents': 'No assigned events',
        'analytics.eventWithoutName': 'Event without name',
        'analytics.selectForDetailedAnalysis': 'Select a {type} to see detailed analysis',
        'analytics.employee': 'employee',
        'analytics.equipment': 'equipment',
        'analytics.performanceTrends': 'Performance trends',
        'analytics.eventDistribution': 'Event distribution',
        'analytics.detailedHistory': 'Detailed history',
        'calendar.date': 'Date',

        // Leave Management
        'leave.vacation': 'Vacation',
        'leave.sickness': 'Sickness',
        'leave.personal': 'Personal',
        'leave.training': 'Training',
        'leave.maternity': 'Maternity/Paternity',
        'leave.other': 'Other',
        'leave.fillRequiredFields': 'Please fill in all required fields',
        'leave.startDateAfterEndDate': 'Start date cannot be after end date',
        'leave.unknown': 'Unknown',
        'leave.saveError': 'Error saving leave request',
        'leave.confirmDelete': 'Are you sure you want to delete this leave request?',
        'leave.deleteError': 'Error deleting leave request',
        'leave.approvalError': 'Error approving leave request',
        'leave.approved': 'Approved',
        'leave.refused': 'Refused',
        'leave.pending': 'Pending',
        'leave.management': 'Leave Management',
        'leave.requests': 'Requests',
        'leave.newRequest': 'New Request',
        'leave.history': 'History',
        'leave.noPendingRequests': 'No pending leave requests',
        'leave.period': 'Period',
        'leave.reason': 'Reason',
        'leave.requestedOn': 'Requested on',
        'leave.approve': 'Approve',
        'leave.refuse': 'Refuse',
        'leave.selectPerson': 'Select a person...',
        'leave.type': 'Leave type',
        'leave.reasonOptional': 'Reason (optional)',
        'leave.reasonPlaceholder': 'Add details about the leave request...',
        'leave.createRequest': '💾 Create request',
        'leave.noHistory': 'No leave history',
        'leave.processedOn': 'Processed on',
        'leave.day': 'day',
        'leave.days': 'days',

        // Equipment Management
        'equipment.typeVehicle': 'Vehicle',
        'equipment.typeElectricTool': 'Electric Tool',
        'equipment.typeManualTool': 'Manual Tool',
        'equipment.typeSafety': 'Safety Equipment',
        'equipment.typeElectricMaterial': 'Electrical Material',
        'equipment.typePlumbing': 'Plumbing Material',
        'equipment.typeScaffolding': 'Scaffolding',
        'equipment.typeCrane': 'Crane',
        'equipment.typeCompressor': 'Compressor',
        'equipment.typeGenerator': 'Generator',
        'equipment.typePump': 'Pump',
        'equipment.typeWelding': 'Welding',
        'equipment.typeMeasure': 'Measurement',
        'equipment.typeComputer': 'Computer',
        'equipment.typeOther': 'Other',
        'equipment.nameRequired': 'Equipment name is required',
        'equipment.saveError': 'Error saving equipment',
        'equipment.confirmDelete': 'Are you sure you want to delete {name}?\n\nThis action is irreversible.',
        'equipment.deleteError': 'Error deleting equipment',
        'equipment.modify': 'Modify Equipment',
        'equipment.new': 'New Equipment',
        'equipment.name': 'Equipment name',
        'equipment.namePlaceholder': 'Ex: Makita Cordless Drill',
        'equipment.type': 'Type',
        'equipment.typePlaceholder': 'Ex: Electric Tool',
        'equipment.brand': 'Brand',
        'equipment.brandPlaceholder': 'Ex: Makita',
        'equipment.model': 'Model',
        'equipment.modelPlaceholder': 'Ex: XDT131',
        'equipment.serialNumber': 'Serial Number',
        'equipment.serialPlaceholder': 'Ex: SNJ123456789',
        'equipment.purchaseDate': 'Purchase Date',
        'equipment.rentalCost': 'Rental Cost ($/day)',
        'equipment.costPlaceholder': 'Ex: 25.50',
        'equipment.nextMaintenance': 'Next Maintenance',
        'equipment.displayColor': 'Display Color',
        'equipment.status': 'Status',
        'equipment.available': '🟢 Available',
        'equipment.unavailable': '🔴 Unavailable',
        'equipment.maintenanceScheduled': 'Maintenance scheduled in {days} {unit}',
        'equipment.maintenanceOverdue': 'Maintenance overdue by {days} {unit}',
        'equipment.notes': 'Notes',
        'equipment.notesPlaceholder': 'Add notes about this equipment (maintenance, issues, etc.)',
        'equipment.equipment': 'Equipment',

        // Dashboard
        'dashboard.title': 'Management Dashboard',
        'dashboard.operationsOverview': 'Operations overview',
        'dashboard.connectedAs': 'Connected as',
        'dashboard.guestMode': 'Guest mode',
        'dashboard.overview': 'Overview',
        'dashboard.resources': 'Resources',
        'dashboard.analytics': 'Analytics',
        'dashboard.unassigned': 'Unassigned',
        'dashboard.processRequests': 'Process requests',
        'dashboard.requireMaintenance': 'require maintenance soon',
        'dashboard.viewEquipment': 'View equipment',
        'dashboard.totalJobs': 'Total Jobs',
        'dashboard.available': 'available',
        'dashboard.completionRate': 'Completion Rate',
        'dashboard.outOf': 'out of',
        'dashboard.personnelUtilization': 'Personnel Utilization',
        'dashboard.assigned': 'assigned',
        'dashboard.equipmentUtilization': 'Equipment Utilization',
        'dashboard.used': 'used',
        'dashboard.jobsByPriority': 'Jobs by Priority',
        'dashboard.jobsByOffice': 'Jobs by Office',
        'dashboard.recentJobs': 'Recent Jobs (last 7 days)',
        'dashboard.noRecentJobs': 'No jobs created recently',
        'dashboard.jobManagement': 'Job Management',
        'dashboard.jobManagementPlaceholder': 'Job management interface to be implemented...',
        'dashboard.resourceManagement': 'Resource Management',
        'dashboard.resourceManagementPlaceholder': 'Resource management interface to be implemented...',
        'dashboard.advancedAnalytics': 'Advanced Analytics',
        'dashboard.advancedAnalyticsPlaceholder': 'Advanced charts and analytics to be implemented...',
        'leave.request': 'request',

        // Priorités
        'priority.low': 'Low',
        'priority.normal': 'Normal',
        'priority.high': 'High',
        'priority.urgent': 'Urgent',

        // Nouveaux statuts
        'status.postponed': 'Postponed',

        // Formulaire JobModal
        'form.form': 'Form',
        'form.gantt': 'Gantt',
        'form.resources': 'Resources',
        'form.projectNumber': 'Project Number',
        'form.projectNumberPlaceholder': 'Ex: G25-1112, MDL-2024-001, CFM-240918',
        'form.clientPlaceholder': 'Client name',
        'form.departmentInCharge': 'Department/Branch in charge',
        'form.selectDepartment': 'Select a department',
        'form.jobName': 'Job name',
        'form.jobDescriptionPlaceholder': 'Ex: Electrical installation, detailed job description...',
        'form.schedulesByDay': 'Schedules by day',
        'form.customizeSchedulesHint': 'Customize schedules for specific days. The "Include weekends" checkbox above controls automatic inclusion.',
        'form.personnelStatistics': 'Personnel statistics',
        'form.total': 'Total',
        'form.planned': 'Planned',
        'form.available': 'Available',
        'form.byDepartment': 'By department/branch',
        'form.byPosition': 'By position',
        'form.subcontractorAdded': 'Subcontractor added successfully',
        'form.addToGlobal': 'Add to global',
        'form.removeFromGlobal': 'Remove from global',
        'form.quickSelectionByDay': 'Quick selection by day',
        'form.managePersonnelForDay': 'Manage personnel for this day',
        'form.manageEquipmentForDay': 'Manage equipment for this day',
        'form.durationInHours': 'Duration in hours',
        'form.openConflictEvent': 'Open conflict event',

        // Job et maintenance
        'job.editExistingEvent': 'Editing an existing event',
        'job.newJobInPlanner': 'New job in planner',
        'job.maintenance': 'Maintenance',
        'job.preventive': 'preventive',

        // Ressources
        'resource.notAssigned': 'Not assigned',

        // Messages de succès JobModal
        'success.eventSaved': 'Event saved successfully',
        'success.jobDeleted': 'Job deleted successfully',
        'success.personnelAddedToEvent': 'Personnel added to the entire event',

        // Messages d'avertissement
        'warning.personnelRemovedFromEvent': 'Personnel removed from the entire event',

        // Erreurs JobModal
        'error.saveError': 'Error while saving',
        'error.deleteError': 'Error while deleting',

        // Confirmations
        'modal.confirmDeleteJob': 'Are you sure you want to delete this job?',

        // Équipements
        'equipment.currentlyOutOfService': 'This equipment is currently out of service',

        // Administration générale
        'admin.notSpecified': 'Not specified',

        // Administration des ressources
        'admin.resource.title': 'Resources Management',
        'admin.resource.subtitle': 'Personnel and Equipment',

        // Authentification admin
        'admin.auth.restrictedAccess': 'Restricted Access',
        'admin.auth.authRequired': 'This section requires administrative authentication.',
        'admin.auth.adminPassword': 'Administrator password',
        'admin.auth.passwordPlaceholder': 'Enter admin password...',
        'admin.auth.hidePassword': 'Hide password',
        'admin.auth.showPassword': 'Show password',
        'admin.auth.authenticate': 'Authenticate',

        // Vues administratives
        'admin.view.grid': 'Grid',
        'admin.view.individual': 'Individual',
        'admin.view.backToList': 'Back to list',

        // Filtres administratifs
        'admin.filter.all': 'All',
        'admin.filter.allTypes': 'All types',
        'admin.filter.availability': 'Availability',
        'admin.filter.searchPlaceholder': 'Name, position, type...',
        'admin.filter.reset': 'Reset filters',
        'admin.filter.management': 'Filter Management',
        'admin.filter.import': 'Import',
        'admin.filter.export': 'Export',
        'admin.filter.newFilter': 'New Filter',
        'admin.filter.createNew': 'Create new filter',
        'admin.filter.name': 'Filter name',
        'admin.filter.namePlaceholder': 'Ex: Personnel Paris Office',
        'admin.filter.description': 'Description',
        'admin.filter.descriptionPlaceholder': 'Optional description',
        'admin.filter.currentCriteria': 'Current criteria to be saved',
        'admin.filter.tab': 'Tab',
        'admin.filter.savedFilters': 'Saved filters',
        'admin.filter.noSavedFilters': 'No saved filters',
        'admin.filter.configureHint': 'Configure your filters and click "New Filter" to save them',
        'admin.filter.createdOn': 'Created on',
        'admin.filter.apply': 'Apply',
        'admin.filter.nameRequired': 'Please provide a name for your filter',
        'admin.filter.savedSuccess': 'Filter saved successfully',
        'admin.filter.applied': 'Filter applied',
        'admin.filter.confirmDelete': 'Are you sure you want to delete this filter?',
        'admin.filter.deleteSuccess': 'Filter deleted',
        'admin.filter.exportSuccess': 'Filters exported successfully',
        'admin.filter.importSuccess': 'Filter(s) imported successfully',
        'admin.filter.importError': 'Error importing filters',

        // Gestion du personnel
        'admin.personnel.management': 'Personnel Management',
        'admin.personnel.add': 'Add Personnel',
        'admin.personnel.contactInfo': 'Contact information',
        'admin.personnel.phone': 'Phone',
        'admin.personnel.email': 'Email',
        'admin.personnel.positionDetails': 'Position details',
        'admin.personnel.skills': 'Skills',
        'admin.personnel.skillsNotSpecified': 'Not specified',
        'admin.personnel.noResults': 'No personnel found with selected criteria',

        // Gestion des équipements
        'admin.equipment.management': 'Equipment Management',
        'admin.equipment.add': 'Add Equipment',
        'admin.equipment.technicalInfo': 'Technical information',
        'admin.equipment.model': 'Model',
        'admin.equipment.serialNumber': 'Serial number',
        'admin.equipment.statusMaintenance': 'Status and maintenance',
        'admin.equipment.condition': 'Condition',
        'admin.equipment.good': 'Good',
        'admin.equipment.lastMaintenance': 'Last maintenance',
        'admin.equipment.nextMaintenance': 'Next maintenance',
        'admin.equipment.notSpecified': 'Not specified',
        'admin.equipment.notPlanned': 'Not planned',
        'admin.equipment.notes': 'Notes',
        'admin.equipment.noNotes': 'No notes',
        'admin.equipment.noResults': 'No equipment found with selected criteria',

        // Gestion des postes
        'admin.position.title': 'Positions',
        'admin.position.management': 'Position Management',
        'admin.position.add': 'Add Position',
        'admin.position.level': 'Level',
        'admin.position.salary': 'Salary',
        'admin.position.noPositions': 'No positions configured',
        'admin.position.createHint': 'Start by creating positions for your company',
        'admin.position.saveSuccess': 'Position saved successfully',

        // Gestion des succursales
        'admin.branch.title': 'Branches',
        'admin.branch.management': 'Branch Management',
        'admin.branch.add': 'Add Branch',
        'admin.branch.active': 'Active',
        'admin.branch.inactive': 'Inactive',
        'admin.branch.noBranches': 'No branches configured',
        'admin.branch.saveSuccess': 'Branch saved successfully',

        // Personnel Modal - General
        'personnel.newPersonnel': 'New Personnel',
        'personnel.general': 'General',
        'personnel.skills': 'Skills',
        'personnel.schedules': 'Schedules',
        'personnel.permissions': 'Permissions',
        'personnel.contact': 'Contact',
        'personnel.photo': 'Photo',
        'personnel.firstName': 'First Name',
        'personnel.firstNamePlaceholder': 'First name...',
        'personnel.lastName': 'Last Name',
        'personnel.lastNamePlaceholder': 'Last name...',
        'personnel.position': 'Position',
        'personnel.selectPosition': 'Select a position...',
        'personnel.branch': 'Branch',
        'personnel.hireDate': 'Hire Date',
        'personnel.status': 'Status',
        'personnel.statusActive': '✅ Active',
        'personnel.statusInactive': '⏸️ Inactive',
        'personnel.statusOnLeave': '🏖️ On Leave',
        'personnel.statusSick': '🤒 Sick',
        'personnel.hourlyRate': 'Hourly Rate ($)',
        'personnel.hourlyRatePlaceholder': 'Ex: 25.00',
        'personnel.annualSalary': 'Annual Salary ($)',
        'personnel.annualSalaryPlaceholder': 'Ex: 50000',
        'personnel.systemAccess': 'System Access',
        'personnel.password': 'Password',
        'personnel.passwordPlaceholder': 'Password...',
        'personnel.passwordChangeHint': 'Leave empty to keep unchanged',
        'personnel.calendarColor': 'Calendar Color',
        'personnel.visibleOnCalendar': 'Visible on calendar',

        // Personnel Modal - Skills
        'personnel.competencies': 'Skills',
        'personnel.addSkill': 'Add a skill...',
        'personnel.certifications': 'Certifications',
        'personnel.addCertification': 'Add a certification...',
        'personnel.trainings': 'Training',
        'personnel.addTraining': 'Add training...',

        // Personnel Modal - Schedules
        'personnel.workSchedules': 'Work Schedules',
        'personnel.monday': 'monday',
        'personnel.tuesday': 'tuesday',
        'personnel.wednesday': 'wednesday',
        'personnel.thursday': 'thursday',
        'personnel.friday': 'friday',
        'personnel.saturday': 'saturday',
        'personnel.sunday': 'sunday',
        'personnel.to': 'to',
        'personnel.specialAvailability': 'Special Availability',
        'personnel.availableWeekendsEmergency': 'Available weekends (emergency)',
        'personnel.availableNightWork': 'Available for night work',
        'personnel.availableTravel': 'Available for travel',

        // Personnel Modal - Permissions
        'personnel.permissionsAccess': 'Permissions and Access',
        'personnel.canModify': 'Can modify data',
        'personnel.canModifyDesc': 'Create, edit and delete jobs',
        'personnel.isCoordinator': 'Coordinator',
        'personnel.isCoordinatorDesc': 'Full access to all features',
        'personnel.canApproveLeaves': 'Can approve leaves',
        'personnel.canApproveLeavesDesc': 'Validate or reject leave requests',
        'personnel.canViewReports': 'Can view reports',
        'personnel.canViewReportsDesc': 'Access to statistics and reports',
        'personnel.canManagePersonnel': 'Can manage personnel',
        'personnel.canManagePersonnelDesc': 'Add, edit and delete employees',
        'personnel.canManageEquipment': 'Can manage equipment',
        'personnel.canManageEquipmentDesc': 'Manage equipment and maintenance',
        'personnel.onlyCoordinatorsCanModify': 'Only coordinators can modify access permissions.',

        // Personnel Modal - Contact
        'personnel.officePhone': 'Office Phone',
        'personnel.cellPhone': 'Cell Phone',
        'personnel.email': 'Email',
        'personnel.address': 'Address',
        'personnel.addressPlaceholder': '123 Example Street',
        'personnel.city': 'City',
        'personnel.cityPlaceholder': 'Thetford Mines',
        'personnel.postalCode': 'Postal Code',
        'personnel.postalCodePlaceholder': 'G1X 1X1',
        'personnel.emergencyContact': 'Emergency Contact',
        'personnel.contactPerson': 'Contact Person',
        'personnel.contactPersonPlaceholder': 'Contact name...',
        'personnel.emergencyPhone': 'Emergency Phone',
        'personnel.medicalInfo': 'Medical Information',
        'personnel.medicalNotes': 'Medical Notes',
        'personnel.medicalNotesPlaceholder': 'Restrictions, limitations...',
        'personnel.allergies': 'Allergies',
        'personnel.allergiesPlaceholder': 'Known allergies...',

        // Personnel Modal - Validation and messages
        'personnel.nameRequired': 'Last name is required',
        'personnel.firstNameRequired': 'First name is required',
        'personnel.positionRequired': 'Position is required',
        'personnel.invalidEmail': 'Invalid email format',
        'personnel.passwordRequiredNew': 'A password is required for a new employee',
        'personnel.personnelModified': 'Personnel modified',
        'personnel.personnelCreated': 'Personnel created',
        'personnel.saveError': 'Error while saving',
        'personnel.personnelDeleted': 'Personnel deleted',
        'personnel.deleteError': 'Error while deleting',
        'personnel.confirmDelete': 'Confirm deletion',
        'personnel.confirmDeleteMessage': 'Are you sure you want to delete {firstName} {lastName}? This action is irreversible.',
        'personnel.delete': 'Delete',
        'personnel.cancel': 'Cancel',
        'personnel.saving': 'Saving...',
        'personnel.modify': 'Edit',
        'personnel.create': 'Create',

        // Personnel Modal Resource - Additions
        'personnel.fillNameFirstName': 'Please fill in first and last name before generating a password',
        'personnel.branchRequired': 'Branch is required',
        'personnel.confirmDeleteMessageSimple': 'Are you sure you want to delete {name}?\n\nThis action is irreversible.',
        'personnel.modifyPersonnel': 'Edit Personnel',
        'personnel.managementC-Secur360': 'C-Secur360 personnel management',
        'personnel.lastNameExample': 'Ex: Smith',
        'personnel.firstNameExample': 'Ex: John',
        'personnel.departmentPlaceholder': 'Selected by position or manual entry',
        'personnel.selectBranch': 'Select a branch',
        'personnel.phone': 'Phone',
        'personnel.authPassword': 'Authentication Password',
        'personnel.authPasswordPlaceholder': 'Password for main authentication',
        'personnel.hidePassword': 'Hide password',
        'personnel.showPassword': 'Show password',
        'personnel.passwordInfo': 'Required to access the application. 24h recognition then password required again.',
        'personnel.generatePasswordHint': '💡 Click on 🔄 to automatically generate a password based on first/last name',
        'personnel.generateAutoPassword': 'Generate automatic password',
        'personnel.generate': 'Generate',
        'personnel.accessLevel': 'Access Level',
        'personnel.accessConsultation': '👁️ View Only',
        'personnel.accessModification': '✏️ Limited Modification',
        'personnel.accessCoordination': '🎯 Coordination',
        'personnel.accessAdministration': '🔑 Full Administration',
        'personnel.accessLevelInfo': 'Defines user permissions in the system',
        'personnel.salaryOptional': 'Salary (optional)',
        'personnel.specialties': 'Specialties',
        'personnel.addSpecialty': 'Add a specialty...',
        'personnel.statusAvailable': '🟢 Available',
        'personnel.statusUnavailable': '🔴 Unavailable',
        'personnel.display': 'Display',
        'personnel.visibilityInfo': 'Uncheck to hide this person from the main calendar',
        'personnel.notes': 'Notes',
        'personnel.notesPlaceholder': 'Add notes about this personnel...',
        'personnel.save': '💾 Save'
    }
};

// Contexte
const LanguageContext = createContext();

// Provider
export function LanguageProvider({ children }) {
    const [currentLanguage, setCurrentLanguage] = useState('fr');

    // Charger la langue depuis localStorage au démarrage
    useEffect(() => {
        const savedLanguage = localStorage.getItem('preferred-language');
        if (savedLanguage && LANGUAGES[savedLanguage]) {
            setCurrentLanguage(savedLanguage);
        }
    }, []);

    // Fonction pour changer de langue
    const changeLanguage = (languageCode) => {
        if (LANGUAGES[languageCode]) {
            setCurrentLanguage(languageCode);
            localStorage.setItem('preferred-language', languageCode);
        }
    };

    // Fonction de traduction
    const t = (key, defaultValue = key) => {
        return translations[currentLanguage]?.[key] || defaultValue;
    };

    // Fonction pour obtenir le nom de la langue actuelle
    const getCurrentLanguageName = () => {
        return LANGUAGES[currentLanguage]?.name || 'Français';
    };

    // Fonction pour obtenir le drapeau de la langue actuelle
    const getCurrentLanguageFlag = () => {
        return LANGUAGES[currentLanguage]?.flag || '🇫🇷';
    };

    const value = {
        currentLanguage,
        changeLanguage,
        t,
        getCurrentLanguageName,
        getCurrentLanguageFlag,
        availableLanguages: Object.values(LANGUAGES)
    };

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
}

// Hook pour utiliser le contexte de langue
export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}

export default LanguageContext;